### ISSUE TITLE
No such file or directory: 'static/images/subreddit/'

### ISSUE THREAD

**Issue by drandreaskrueger** [DrPugsley/Reddit-Archive-Host#1]
thanks for providing us with your tool. The other ones don't seem to work (e.g. [this](https://github.com/MalloyDelacroix/DownloaderForReddit/issues/59))

I got yours *almost* working:

```
python3 Post-Archiver.py philosophy day 5
Fetching posts: [3/5]
All done!
```

and there is e.g a 140kB file b2yvpj.json - hooray!

The server comes up, the subreddit is there, the date is correct, and I can even see 3 posts there.

but then when I click on a post, I get this:
```
python3 Flask-Host.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Mar/2019 01:53:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 01:53:38] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 01:53:38] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Mar/2019 01:53:41] "GET /r/philosophy HTTP/1.1" 200 -
0
127.0.0.1 - - [20/Mar/2019 01:53:42] "GET /r/philosophy/date/2019-03-20/1 HTTP/1.1" 200 -
[2019-03-20 01:53:45,865] ERROR in app: Exception on /r/philosophy/post/b2yvpj [GET]
Traceback (most recent call last):
  File "~/Documents/Code/DrPugsley_Reddit-Archive-Host/env/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "~/Documents/Code/DrPugsley_Reddit-Archive-Host/env/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "~/Documents/Code/DrPugsley_Reddit-Archive-Host/env/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "~/Documents/Code/DrPugsley_Reddit-Archive-Host/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "~/Documents/Code/DrPugsley_Reddit-Archive-Host/env/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "~/Documents/Code/DrPugsley_Reddit-Archive-Host/env/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Flask-Host.py", line 71, in thread
    for a in os.listdir('static/images/{}/'.format(sub)):
FileNotFoundError: [Errno 2] No such file or directory: 'static/images/philosophy/'
127.0.0.1 - - [20/Mar/2019 01:53:45] "GET /r/philosophy/post/b2yvpj HTTP/1.1" 500 -
```

and in the frontend this:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

I don't care about images.  

You must probably simply catch the exception if an image is not there ?

**Comment by drandreaskrueger** [comment]
Hah. SOLVED !

    mkdir static/images/philosophy -p

and then it works.

so, your 

    python3 Post-Archiver.py philosophy day 5

had simply forgotten to create that  subfolder `static/images/philosophy`

that should be easy to fix, no?

**Comment by drandreaskrueger** [comment]
probably even easier, this is enough already, to fix the problem:

    mkdir static/images/ -p

because now, this command worked flawlessly in a different subreddit:

    python3 Post-Archiver.py collapse month 100
